apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wcsdeploycontroller
  namespace: {{ .Values.Common.NameSpace }}
spec:
  replicas: {{ .Values.DeployController.Replicas }}
  template:
    metadata:
      labels:
        component: wcsdeploycontroller
        group: wcsdevops
    spec:
      {{- if .Values.DeployController.NodeSelector }}
      nodeSelector:
        {{- range $key, $value := .Values.DeployController.NodeSelector }}
          {{ $key }}：{{ $value }}
        {{- end }}
      {{- end }}
      containers:
      - name: wcsdeploycontroller
        image: "{{ .Values.DeployController.Image }}:{{ .Values.DeployController.Tag }}"
        resources:
          requests:
            cpu: 0.5m
            memory: 2048Mi
          limits:
            cpu: 2
            memory: 4096Mi
        env:
{{- if .Values.DeployController.EnvParameters }}
     {{- range $key, $value := .Values.DeployController.EnvParameters }}
        {{- if $value }}
        - name: {{ $key | quote}}
          value: {{ $value | quote}}
        {{- end }}
     {{- end }}
{{- end }}
        ports:
        - containerPort: 8080
          name: db8080
          protocol: TCP
        - containerPort: 50000
          name: db50000
          protocol: TCP
---

apiVersion: v1
kind: Service
metadata:
  name: wcsdeploycontroller
  namespace: {{ .Values.Common.NameSpace }}
spec:
  type: NodePort
  ports:
  - port: 8080
    name: port8080
    targetPort: 8080
    nodePort: 31899
  - port: 50000
    name: port50000
    targetPort: 50000
  selector:
    component: wcsdeploycontroller