Common:
  NameSpace: default

VaultConsul:
  Replicas: 1
  VaultImage: docker.io/vault
  VaultTag: 0.9.5
  ConsulImage: docker.io/consul
  ConsulTag: 1.0.6
  Enable: true
  NodeSelector:
  EnvParameters:
      Vault:
      Consul:

DeployController:
  Replicas: 1
  Image: deploycontroller
  Tag: latest
  EnvParameters:
    InCluster: true
    VaultUrl:
    VaultToken:
    KubernetesUrl:
    BundleRepo: http://nexus:8081/nexus/content/repositories/releases/commerce
    DockerRepo:
    DockerRepoPwd:
    DockerRepoUser:
    HelmChartsRepo:
  NodeSelector:

Nexus:
  Replicas: 1
  Image: sonatype/nexus
  Tag: latest
  NodePort: true
  Enable: false
  NodeSelector:
  EnvParameters:
