{{- if and .Values.Common.SessionAffinity.Enable  .Values.Common.SessionAffinity.LoadBalanceAddress }}

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.Common.Tenant }}{{ .Values.Common.EnvironmentName}}{{ .Values.Common.EnvironmentType }}-sessionaffinity-tsapp
  namespace: {{ .Values.Common.NameSpace }}
  annotations:
    nginx.ingress.kubernetes.io/secure-backends: "true"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/session-cookie-name: INGRESSCOOKIE
    nginx.ingress.kubernetes.io/session-cookie-hash: sha1
    group: {{ .Values.Common.Tenant }}{{ .Values.Common.EnvironmentName}}{{ .Values.Common.EnvironmentType }}
spec:
  tls:
  - hosts:
    - {{ .Values.Common.Tenant }}{{ .Values.Common.EnvironmentName}}{{ .Values.Common.EnvironmentType }}ts-app.{{ .Values.Common.NameSpace }}.svc.cluster.local
    secretName: {{ .Values.Common.Tenant }}{{ .Values.Common.EnvironmentName}}{{ .Values.Common.EnvironmentType }}ts-app-certificate
  rules:
  - host: {{ .Values.Common.Tenant }}{{ .Values.Common.EnvironmentName}}{{ .Values.Common.EnvironmentType }}ts-app.{{ .Values.Common.NameSpace }}.svc.cluster.local
    http:
      paths:
      - path:
        backend:
          serviceName: {{ .Values.Common.Tenant }}{{ .Values.Common.EnvironmentName}}{{ .Values.Common.EnvironmentType }}ts-app
          servicePort: 5443
{{- end }} 